{% set version = '0.4.4' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-qualpalr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qualpalr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qualpalr/qualpalr_{{ version }}.tar.gz
  sha256: 2214246a43baf0c2db7e93909dc34ba6746815982957adcbf08deab00f85aa8e

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib('c') }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('m2w64_c') }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-rcpparmadillo >=0.7.600.1.0
    - r-assertthat
    - r-randtoolbox >=1.17
  run:
    - r-base
    - r-rcpp
    - r-rcpparmadillo >=0.7.600.1.0
    - r-assertthat
    - r-randtoolbox >=1.17

test:
  commands:
    - $R -e "library('qualpalr')"           # [not win]
    - "\"%R%\" -e \"library('qualpalr')\""  # [win]

about:
  home: https://jolars.github.io/qualpalr/
  license: GPL-3.0-only
  summary: Automatic generation of maximally distinct qualitative color palettes, optionally
    tailored to color deficiency. A list of colors or a subspace of a color space is
    used as input and then projected to the DIN99d color space, where colors that are
    maximally distinct are chosen algorithmically.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
